server:
 port: 8082
 
spring:
 application:
    name: customer-management
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customer-management
    username: postgres
    password: root
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost

springdoc:
  packagesToScan: com.otsi.retail.customerManagement
  
getbarcodes:
  url: http://localhost:8081/newsale/getbarcodes
getNewSaleWithHsn: 
  url: http://localhost:8083/hsnDetails/getHsnDetails
logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/customer-management.log
    level:
      com.otsi.retail.customerManagement.service: DEBUG   
