server:
 port: 8088
 
 
spring:
 application:
    name: promo-exchange-service
    
 datasource:
    platform: postgres
    url: jdbc:postgresql://promo-exchange-pos:5432/promo-exchange
    username: postgres
    password: root
    
  
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL81Dialect
   show-sql: true



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.100.82.250:8088/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
  
springdoc:
  packagesToScan: com.promoexchangeapi
  
#==============================================RESTCALL==================================

savecustomer_url: http://new-sale-api:8081/customer/savecustomerdetails
getdeliveryslip_url: http://new-sale-api:8081/newsale/getdeliveryslip
getreturnslip_url: http://customer-management:8082/customer/getAllListOfReturnSlips
GET_DS_DETAILS_FROM_NEWSALE_URl : http://new-sale-api:8081/newsale/getdeliveryslip


