server:
 port: 8088
 
 
spring:
 application:
    name: promo-exchange-service
    
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/promo-exchange
    username: postgres
    password: root
    
  
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL81Dialect
   show-sql: true



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
  
springdoc:
  packagesToScan: com.promoexchangeapi
  

