server:
 port: 8085
 
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
  
spring:
 application:
    name: connection-pool
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/connectionpool
    username: postgres
    password: root
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true