server:
 port: 8081

spring:
 application:
    name: new-sale-service 
 datasource:
    platform: postgres
    url: jdbc:postgresql://10.100.238.45:5432/newSale
    username: postgres
    password: Otsi@123
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/newsale.log    
    level:
      com.otsi.retail.newSale.serviceimpl: DEBUG   
springdoc:
  packagesToScan: com.otsi.retail.newSale
  
