apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-store-mapping.fullname" . }}
  labels:
    {{- include "user-store-mapping.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "user-store-mapping.selectorLabels" . | nindent 4 }}
