server:
 port: 8084
 
spring:
 application:
    name: debit-notes
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/debit-notes
    username: postgres
    password: Vasavi
    initializaion.mode: always
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
   springdoc:
    packagesToScan: com.newsaleapi
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/debit-notes.log    
    level:
      com.otsi.retail.debitnotes.serviceimpl: DEBUG  